
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fdfed_backend
    environment:
      - PORT=3000
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: fdfed_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
